apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: sample-foo-operator-role
      labels:
        app: sample-foo-operator-test
    rules:
      - apiGroups:
          - "apps"
        resources:
          - deployments
        verbs:
          - create
          - list
          - get
          - update
          - delete
          - watch
          - patch
      - apiGroups:
          - apiextensions.k8s.io
        resources:
          - customresourcedefinitions
        verbs:
          - get
          - list
      - apiGroups:
          - samplecontroller.k8s.io
        resources:
          - foos
          - foos/status
        verbs:
          - create
          - get
          - list
          - update
          - patch
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: sample-foo-operator-binding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: sample-foo-operator-role
    subjects:
    - kind: ServiceAccount
      name: sample-foo-operator-sa
      namespace: default
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sample-foo-operator-sa
      labels:
        app: sample-foo-operator-test